language: ruby
dist: trusty
sudo: false
cache:
  bundler: true
  apt: true
  directories:
    - node_modules
rvm:
  - 2.5.1
env:
  global:
    - COVERAGE=true
    - PRECOMMIT=false
before_install:
  - psql -c 'create database railsprojecttemplate_travis;' -U postgres
  - "export DISPLAY=:99.0"
  - gem install bundler --no-document
bundler_args: --without development
before_script:
  - mv .env.test.travis .env.test
  - bin/rails db:create
  - bin/rails db:test:prepare
  - export TZ=Europe/Berlin
script:
  - bin/rspec spec
addons:
  postgresql: 9.4
notifications:
  email: false
